
def names_mapping():
    mapping = {'artifacts_size': 'Storage: artifacts size',
               'artifacts_count': 'Storage: artifacts count',
               'binaries_size': 'Storage: binaries size',
               'binaries_count': 'Storage: binaries count',
               'items_count': 'Storage: items count',
               'number_of_permissions': 'Number of permissions',
               'internal_groups': 'Number of internal groups',
               'number_of_users': 'Number of users',
               'maven': 'Maven repositories',
               'generic': 'Generic repositories',
               'docker': 'Docker repositories',
               'npm': 'Npm repositories',
               'pypi': 'Pypi repositories',
               'gradle': 'Gradle repositories',
               'nuget': 'Nuget repositories',

               'n_ent_trials': 'Number of Enterprise trials in the last year',
               'unresolved_jira_cases': 'Number of unresolved Jira cases in the last year',
               'n_contacts': 'Number of contacts',
               'n_trials': 'Number of trials in the last year',
               'n_active_contracts': 'Number of active contracts',
               'pricing_views': 'Number of views in the pricing page',
               'artifactory_views': 'Number of views in the artifactory page',
               'xray_views': 'Number of views in the Xray page',
               'support_views': 'Number of views in the support page',
               'knowledge_views': 'Number of views in the knowledge-base page',
               'is_cotermed': 'Is previously co-termed?',
               'n_sessions_last_year': 'Number of sessions in the last year',
               'n_xray_sessions_last_year': 'Number of Xray sessions in the last year',
               'n_cases_last_year': 'Number of cases in the last year',
               'avg_resolution_days': 'Average resolution days for a case',
               'industry_group': 'Industry', # - TODO
               'total_employees_range': 'Number of employees (range)',  # - TODO
               'company_age': 'Company age (years)',  # - TODO
               'company_type': 'Company type',

               'seniority': 'Seniority in JFrog (months)', # - TODO
               'days_from_contact_added': 'Number of days since last contact added',
               'days_from_artifacts_size_change': 'Number of days since artifacts size changed',
               'days_from_artifacts_count_change': 'Number of days since artifacts count changed',
               'days_from_binaries_size_change': 'Number of days since binaries size changed',
               'days_from_binaries_count_change': 'Number of days since binaries count changed',
               'days_from_items_count_change': 'Number of days since items count changed',
               'days_from_permissions_change': 'Number of days since number of permissions changed',
               'days_from_internal_groups_change': 'Number of days since number of internal groups changed',
               'days_from_users_change': 'Number of days since number of users changed',
               'total_security_policies': 'Number of secured policies (Xray)', # - TODO
               'days_since_xray_task': 'Number of days since last Xray task',
               'n_sent': 'Number of Emails sent',
               'days_since_reply': 'Number of days since the account replayed to an Email',
               'days_since_sent': 'Number of days since an Email sent to the account',

               'n_repos': 'Number of repositories',
               'n_env': 'Number of environments',
               'n_tech': 'Number of technologies',
               'n_jira_cases': 'Number of Jira cases in the last year',
               'n_env_monthly_growth': 'Number of environments monthly incline',
               'n_env_quarter_growth': 'Number of environments quarterly incline',
               'n_tech_monthly_growth': 'Number of technologies monthly incline',
               'n_tech_quarter_growth': 'Number of technologies quarterly incline',
               'leading_tech': 'Leading technology',
               'generic_monthly_growth': 'Generic monthly incline',
               'gradle_monthly_growth': 'Gradle monthly incline',
               'npm_monthly_growth': 'Npm monthly incline',
               'nuget_monthly_growth': 'Nuget monthly incline',
               'maven_monthly_growth': 'Maven monthly incline',
               'docker_monthly_growth': 'Docker monthly incline',
               'pypi_monthly_growth': 'Pypi monthly incline',
               'artifacts_count_monthly_growth': 'Storage: artifacts count monthly incline',
               'artifacts_size_monthly_growth': 'Storage: artifacts size monthly incline',
               'binaries_count_monthly_growth': 'Storage: binaries count monthly incline',
               'binaries_size_monthly_growth': 'Storage: binaries size monthly incline',
               'items_count_monthly_growth': 'Storage: items count monthly incline',
               'number_of_users_monthly_growth': 'Number of users monthly incline',
               'n_repos_monthly_growth': 'Number of repositories monthly incline',
               'number_of_permissions_monthly_growth': 'Number of permissions monthly incline',
               'internal_groups_monthly_growth': 'Number of internal groups monthly incline',
               'generic_quarter_growth': 'Generic quarterly incline',
               'maven_quarter_growth': 'Generic quarterly incline',
               'docker_quarter_growth': 'Docker quarterly incline',
               'npm_quarter_growth': 'Npm quarterly incline',
               'gradle_quarter_growth': 'Gradle quarterly incline',
               'nuget_quarter_growth': 'Nuget quarterly incline',
               'pypi_quarter_growth': 'Pypi quarterly incline',
               'n_security_contacts': 'Number of security contacts',
               'n_cases_last_3_months': 'Number of cases in the last 3 months',
               'artifacts_count_quarter_growth': 'Storage: artifacts count quarterly incline',
               'artifacts_size_quarter_growth': 'Storage: artifacts size quarterly incline',
               'binaries_count_quarter_growth': 'Storage: binaries count quarterly incline',
               'binaries_size_quarter_growth': 'Storage: binaries size quarterly incline',
               'items_count_quarter_growth': 'Storage: items count quarterly incline',
               'number_of_users_quarter_growth': 'Number of users quarterly incline',
               'n_repos_quarter_growth': 'Number of repositories quarterly incline',
               'number_of_permissions_quarter_growth': 'Number of permissions quarterly incline',
               'internal_groups_quarter_growth': 'Number of internal groups quarterly incline',
               'revenue_range': 'Company revenue (range)', # - TODO
               'n_ent_mentioned_sessions': 'Number of times enterprise mentioned in sessions',
               'n_ha_mentioned_sessions': 'Number of times high-availability mentioned in sessions',
               'n_xray_mentioned_sessions': 'Number of times xray mentioned in sessions',
               'n_competitor_mentioned_sessions': 'Number of times competitors mentioned in sessions',}
    return mapping
