
def names_mapping():
    mapping = {'artifacts_size': 'Storage: artifacts size',
               'artifacts_count': 'Storage: artifacts count',
               'binaries_size': 'Storage: binaries size',
               'binaries_count': 'Storage: binaries count',
               'items_count': 'Storage: items count',
               'number_of_permissions': 'Number of permissions',
               'internal_groups': 'Number of internal groups',
               'number_of_users': 'Number of users',
               'maven': 'Maven repositories',
               'generic': 'Generic repositories',
               'docker': 'Docker repositories',
               'n_ent_trials': 'Number of Enterprise trials last two years',
               'n_contacts': 'Number of contacts',
               'n_active_contracts': 'Number of active contracts',
               'is_cotermed': 'Is previously co-termed?',
               'months_from_upgrade': 'Number of months passed since upgrade from Pro to Pro X',
               'n_sessions_last_year': 'Number of sessions last year',
               'n_cases_last_year': 'Number of cases last year',
               'avg_resolution_days': 'Average resolution days for a case',
               'industry_group': 'Industry',
               'total_employees_range': 'Number of employees (range)',
               'company_age': 'Company age (years)',
               'seniority': 'Seniority in JFrog (months)',
               'days_from_contact_added': 'Number of days since last contact added',
               'days_from_artifacts_size_change': 'Number of days since artifacts size changed',
               'days_from_artifacts_count_change': 'Number of days since artifacts count changed',
               'days_from_binaries_size_change': 'Number of days since binaries size changed',
               'days_from_binaries_count_change': 'Number of days since binaries count changed',
               'days_from_items_count_change': 'Number of days since items count changed',
               'days_from_permissions_change': 'Number of days since number of permissions changed',
               'days_from_internal_groups_change': 'Number of days since number of internal groups changed',
               'days_from_users_change': 'Number of days since number of users changed',
               'total_security_policies': 'Number of secured policies (Xray)',
               'days_since_xray_task': 'Number of days since Xray task',
               'n_sent': 'Number of Emails sent',
               'days_since_reply': 'Number of days since the account replayed to an Email',
               'days_since_sent': 'Number of days since an Email sent to the account',
               'n_repos': 'Number of repositories',
               'leading_tech': 'Leading technology',
               'generic_monthly_growth': 'Generic monthly growth',
               'maven_monthly_growth': 'Generic monthly growth',
               'docker_monthly_growth': 'Docker monthly growth',
               'artifacts_count_monthly_growth': 'Artifacts count monthly growth',
               'artifacts_size_monthly_growth': 'Artifacts size monthly growth',
               'binaries_count_monthly_growth': 'Binaries count monthly growth',
               'binaries_size_monthly_growth': 'Binaries size monthly growth',
               'items_count_monthly_growth': 'Items count monthly growth',
               'number_of_users_monthly_growth': 'Number of users monthly growth',
               'n_repos_monthly_growth': 'Number of repositories monthly growth',
               'number_of_permissions_monthly_growth': 'Number of permissions monthly growth',
               'internal_groups_monthly_growth': 'Number of internal groups monthly growth',
               'generic_quarter_growth': 'Generic quarterly growth',
               'maven_quarter_growth': 'Generic quarterly growth',
               'docker_quarter_growth': 'Docker quarterly growth',
               'npm_quarter_growth': 'Npm quarterly growth',
               'artifacts_count_quarter_growth': 'Artifacts count quarterly growth',
               'artifacts_size_quarter_growth': 'Artifacts size quarterly growth',
               'binaries_count_quarter_growth': 'Binaries count quarterly growth',
               'binaries_size_quarter_growth': 'Binaries size quarterly growth',
               'items_count_quarter_growth': 'Items count quarterly growth',
               'number_of_users_quarter_growth': 'Number of users quarterly growth',
               'n_repos_quarter_growth': 'Number of repositories quarterly growth',
               'number_of_permissions_quarter_growth': 'Number of permissions quarterly growth',
               'internal_groups_quarter_growth': 'Number of internal groups quarterly growth'}
    return names_mapping